version: "3.5"
services:

  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb/db:/data/db
    networks:
      - organic

  adminmongo:
    image: mrvautin/adminmongo
    container_name: "adminmongo"
    ports:
      - "1234:1234"
    networks:
      - organic

  chrome:
    image: selenium/standalone-chrome-debug
    container_name: "selenium"
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      - organic

  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    volumes:
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/config:/verdaccio/conf"
      - "./verdaccio/plugins:/verdaccio/plugins"
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    networks:
      - organic

networks:
  organic:
    driver: bridge
